version: '2'
services:
    avonniv-app:
        image: avonniv
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://avonniv-mysql:3306/avonniv?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    avonniv-mysql:
        extends:
            file: mysql.yml
            service: avonniv-mysql
